spring:
  datasource:
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
